const declarations = {
    SETPLAYERS: "SETPLAYERS",
    SETNEWPLAYERS: "SETNEWPLAYERS",
    SETSELECTEDPARAMS: "SETSELECTEDPARAMS",
    SETLOADED: "SETLOADED"
}
export const { SETPLAYERS, SETNEWPLAYERS, SETSELECTEDPARAMS, SETLOADED } = declarations;