const declarations = {
    SETPLAYERS: "SETPLAYERS",
    SETNEWPLAYERS: "SETNEWPLAYERS",
    SETSELECTEDPARAMS: "SETSELECTEDPARAMS",
    SETLOADOUTPARAMS: "SETLOADOUTPARAMS",
    SETLOADED: "SETLOADED",
    SETTYPE: "SETTYPE",
    TOGGLECLASS: "TOGGLECLASS",
    SETLOADOUTS: "SETLOADOUTS",
}
export const { 
    SETPLAYERS, 
    SETNEWPLAYERS, 
    SETSELECTEDPARAMS, 
    SETLOADED, 
    SETTYPE, 
    TOGGLECLASS, 
    SETLOADOUTS, 
    SETLOADOUTPARAMS 
} = declarations;