const declarations = {
    SETPLAYERS: "SETPLAYERS",
    SETNEWPLAYERS: "SETNEWPLAYERS",
    SETSELECTEDPARAMS: "SETSELECTEDPARAMS",
    SETLOADED: "SETLOADED",
    SETTYPE: "SETTYPE",
    TOGGLECLASS: "TOGGLECLASS",
    SETLOADOUTS: "SETLOADOUTS",
}
export const { SETPLAYERS, SETNEWPLAYERS, SETSELECTEDPARAMS, SETLOADED, SETTYPE, TOGGLECLASS, SETLOADOUTS } = declarations;